#!/bin/bash

set -euo pipefail

VERT='\033[0;32m'
JAUNE='\033[1;33m'
NC='\033[0m'

echo -e "${VERT}                                   ▄▄                    ${NC}"
echo -e "${VERT}                  █▄                ██       █▄  █▄      ${NC}"
echo -e "${VERT}       ▄          ██                ██      ▄██▄▄██▄     ${NC}"
echo -e "${VERT} ▄▀▀█▄ ████▄▄███▀ ████▄ ▄██▀█ ████▄ ██ ▄▀▀█▄ ██  ██ ▄██▀█${NC}"
echo -e "${VERT} ▄█▀██ ██   ██    ██ ██ ▀███▄ ██ ██ ██ ▄█▀██ ██  ██ ▀███▄${NC}"
echo -e "${VERT}▄▀█▄██▄█▀  ▄▀███▄▄██ ███▄▄██▀▄████▀▄██▄▀█▄██▄██ ▄███▄▄██▀${NC}"
echo -e "${VERT}                              ██                         ${NC}"
echo -e "${VERT}                              ▀                          ${NC}"

echo -e "${JAUNE}Bienvenue dans le script de configuration Archsplatts Void Linux!${NC}\n"

if [ -t 0 ]; then
    read -p "Appuyez sur Entrée pour continuer... "
fi  

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[1/6] Mise à jour de Void${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

sudo xbps-install -Syu

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[2/6] Installation des paquets${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

	PKGS=(
		"LACT"
		"alacritty"
		"bat"
		"btop"
		"cups"
		"dust"
		"epson-inkjet-printer-escpr"
		"eza"
		"fastfetch"
		"flatpak"
		"galculator"
		"git"
		"gnome-calendar"
		"gnome-disk-utility"
		"impression"
		"kvantum"
		"lightdm-gtk-greeter-settings"
		"lollypop"
		"menulibre"
		"mesa-vulkan-radeon"
		"micro"
		"mugshot"
		"noto-fonts-cjk"
		"noto-fonts-emoji"
		"noto-fonts-ttf"
		"octoxbps"
	    "papirus-folders"
		"papirus-icon-theme"
		"qbittorrent"
		"qt5-styleplugins"
		"qt5ct"
		"qt6ct"
		"redshift-gtk"
		"rofi"
		"simple-scan"
		"starship"
		"socklog-void"
		"system-config-printer"
		"terminus-font"
		"thunar-archive-plugin"
		"thunderbird"
		"timeshift"
		"trash-cli"
		"ufw"
		"unzip"
		"vulkan-loader"
		"xfce4-screenshooter"
		"xfce4-whiskermenu-plugin"
		"xmirror"
		"xtools"
		"xz"
		"yazi"
		"zathura"
		"zathura-pdf-mupdf"
		"zip"
		"zsh"
		"zsh-autosuggestions"
		"zsh-syntax-highlighting"		
	)

sudo xbps-install -Sy "${PKGS[@]}"

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[3/6] Ajout du dépôt Flathub${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[4/6] Shell & services${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

chsh -s /bin/zsh
sudo ln -s /etc/sv/cupsd /var/service/
sudo ln -s /etc/sv/nanoklogd /var/service
sudo ln -s /etc/sv/socklog-unix /var/service
sudo ln -s /etc/sv/ufw /var/service/
sudo ufw enable

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[5/6] Copie des dotfiles${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

mkdir -p $HOME/.local/share/applications
mkdir -p $HOME/.local/share/icons
mkdir -p $HOME/.local/share/fonts
mkdir -p $HOME/.local/share/themes
mkdir -p $HOME/.scripts
cp -r $HOME/void-config-XFCE/config/* $HOME/.config
cp -r $HOME/void-config-XFCE/applications/* $HOME/.local/share/applications
cp -r $HOME/void-config-XFCE/scripts/* $HOME/.scripts
cp $HOME/void-config-XFCE/sunken-tower.png $HOME/Images/
sudo cp sunken-tower.png /usr/share/backgrounds
sudo cp 018.png /usr/share/void-artwork/
cp $HOME/void-config-XFCE/zshrc $HOME/.zshrc
chmod u+x $HOME/.scripts/*

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[6/6] Catppuccin papirus folders${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

git clone https://github.com/catppuccin/papirus-folders.git
cd papirus-folders
sudo cp -r src/* /usr/share/icons/Papirus
papirus-folders -C cat-mocha-teal
cd ~
rm -rf papirus-folders

echo -e "${VERT}╔════════════════════════════════════════╗${NC}"
echo -e "${VERT}║  Installation terminée avec succès !   ║${NC}"
echo -e "${VERT}╚════════════════════════════════════════╝${NC}\n"

echo -e "${JAUNE}⚠ Veuillez redémarrer votre système pour appliquer tous les changements.${NC}\n"
