#!/bin/bash

options="ArchWiki\0icon\x1farchlinux
BraveSearch\0icon\x1fbrave
Korben\0icon\x1fkorben
MangoDocs\0icon\x1fmango
Movix\0icon\x1fcom.github.artemanufrij.playmyvideos
ProtonDB\0icon\x1fprotondb
Twitch\0icon\x1ftwitch
Youtube\0icon\x1fyoutube"

selection=$(echo -e "$options" | rofi -dmenu -show-icons -icon-theme "Papirus" -config ~/.config/rofi/web-menu.rasi)

if [[ -n "$selection" ]]; then
    case "$selection" in
		"ArchWiki")
   			brave-origin https://wiki.archlinux.org/title/Main_page
   			;;
   		"BraveSearch")
   		   	brave-origin https://search.brave.com 
   		   	 ;;  
  		"Korben")
  			brave-origin https://korben.info
  			;;          
		"MangoDocs")
			brave-origin https://mangowm.github.io/docs
			;;
		"Movix")
			brave-origin https://movix.bet
			;;
        "ProtonDB")
            brave-origin https://www.protondb.com
            ;;
		"Twitch")
			firefox https://www.twitch.tv/eloetcraquotte
            ;;
        "Youtube")                    
            brave-origin https://www.youtube.com
             ;; 
    esac
fi   
